/**
 * Host half for @dsh-external/dsh-element-picker. There is nothing to do on the host: the whole
 * feature is the browser half (`./client`), declared by `dsh.client` in
 * package.json. Generated by scripts/build.mjs — do not edit by hand.
 */
export const name = "@dsh-external/dsh-element-picker"
export const inject = []
export function apply() {}
